spring.application.name=matchnews-back

spring.sql.init.mode=always

spring.datasource.url=jdbc:mysql://localhost:3306/matchnews?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver